### ISSUE TITLE
jQuery.live() call triggers incorrect "bind(...) called incorrectly"

### ISSUE THREAD

**Issue by tghw** [padolsey-archive/jquery.lint--old#1]
Triggered with something along the lines of:
    $('[name="Foo"], [name="Bar"]').live("keypress", function(e) { ... });

Warning:
    More info:
    You passed:  ["live.keypress.[name="Foo"],|[name="Bar"]", "[name="Foo"], [name="Bar"]", function()]
    Available signatures include:
    bind(eventType, [eventData], handler(eventObject))

We are using the right-click fix for live() from http://dev.jquery.com/ticket/4197, but removing that doesn't change anything. The live events work just fine, so I think jQLint is just being to strict about how bind() is called.

**Comment by padolsey** [comment]
This was caused by jQuery Lint expecting the second argument to bind() being a function (handler) or a data object (type:'object:map').

You seem to be passing a string as data, instead of an object. I've fixed it so it now works with basically anything (apart from a function). Strictly, it should be a map of data (See: http://api.jquery.com/bind/), but I think I'm gonna let this one through. 

Download the latest version of Lint. Let me know if you still get the bug. Thanks! :)

**Comment by tghw** [comment]
I'm not calling bind() directly, that's the way jQuery seems to call it from live() in 1.3.2. (http://github.com/jquery/jquery/blob/1.3.2/src/event.js#L547) 1.4 seems to call bind() with an object like jQLint is expecting. Looks to me like the fix worked.
