### ISSUE TITLE
$.getJSON() triggers 'jQuery.get(...) called incorrectly'

### ISSUE THREAD

**Issue by tghw** [padolsey-archive/jquery.lint--old#5]
Code:
    $.getJSON('/Foo/Bar', function() {...});

Warning:
    You passed:  ["/Foo/Bar", function(), undefined, "json"]
    Available signatures include:
    jQuery.get(url, [data], [callback(data, textStatus, XMLHttpRequest)], [dataType])

jQuery 1.3.2 intentionally passes the `undefined` callback parameter to get() from getJSON():
    // Snip from jQuery 1.3.2
    getJSON: function( url, data, callback ) {
        return jQuery.get(url, data, callback, "json");
    },

**Comment by padolsey** [comment]
Hmm, I'm not sure that's correct usage, but I guess it doesn't matter since it's internal. I've fixed it, now getJSON is checked alongside other jQuery helper functions (under the jQuery namespace) - which should suppress the internal misuse. http://github.com/jamespadolsey/jQuery-Lint/commit/8e4d4b478b1293a8ad7486842dcb23b4f3aa91b1

**Comment by tghw** [comment]
Great, thanks!
